"""
RAG System for SermonAudio Analytics

Implements Retrieval-Augmented Generation for querying sermon analytics data
using ChromaDB for vector storage and configurable embedding providers.
Answers are generated by the app's LLM stack (LLMManager) from retrieved
sermon stats; template answers remain only as an offline fallback.
"""

import logging
import uuid
from datetime import datetime
from typing import Any

import chromadb
from chromadb.config import Settings

# Import the new embedding manager
try:
    from .embedding_manager import EmbeddingManager, create_embedding_manager  # noqa: F401
except ImportError:
    # Handle direct execution
    from embedding_manager import create_embedding_manager

try:
    from src.llm_manager import LLMManager
except ImportError:
    LLMManager = None  # type: ignore[assignment,misc]

logger = logging.getLogger(__name__)

MAX_RETRIEVAL_WIDTH = 200
MAX_PROMPT_SERMONS = 25
MAX_HISTORY_PAIRS = 6


class SermonAnalyticsRAG:
    """RAG system for sermon analytics queries with configurable embedding providers"""

    def __init__(
        self, db_path: str = "analytics_vector_db",
        embedding_config: dict[str, Any] | None = None,
        llm_config: dict[str, Any] | None = None,
    ):
        self.db_path = db_path
        self.embedding_config = embedding_config or self._get_default_embedding_config()
        self.llm_config = llm_config
        self.llm_manager: LLMManager | None = self._create_llm_manager()
        self.reset_notice: str | None = None
        self.embedding_manager = None
        self.client = None
        self.collection = None
        self._initialize_components()

    def _create_llm_manager(self) -> LLMManager | None:
        """Create the LLM manager used to answer questions; None means offline mode"""
        if LLMManager is None:
            logger.warning(
                "src.llm_manager unavailable; analytics chat answers will use "
                "offline templates"
            )
            return None
        if not self.llm_config:
            logger.warning(
                "No LLM configuration provided; analytics chat answers will use "
                "offline templates"
            )
            return None
        try:
            return LLMManager(self.llm_config)
        except Exception as e:
            logger.warning(f"Failed to initialize LLM manager for analytics chat: {e}")
            return None

    def _get_default_embedding_config(self) -> dict[str, Any]:
        """Get default embedding configuration if none provided"""
        return {
            'primary': {
                'provider': 'hash',
                'dimensions': 384
            },
            'fallback': []
        }

    def _initialize_components(self):
        """Initialize ChromaDB and embedding manager"""
        try:
            # Initialize embedding manager
            try:
                self.embedding_manager = create_embedding_manager(self.embedding_config)
                provider_info = self.embedding_manager.get_current_provider_info()
                logger.info(
                    f"Initialized embedding provider: {provider_info['provider']} "
                    f"(model: {provider_info['model']}, dimensions: {provider_info['dimensions']})"
                )
            except Exception as e:
                logger.error(f"Failed to initialize embedding manager: {e}")
                raise

            # Initialize ChromaDB client
            self.client = chromadb.PersistentClient(
                path=self.db_path,
                settings=Settings(anonymized_telemetry=False)
            )

            # Check if collection exists and validate embedding dimensions
            current_dimensions = self.embedding_manager.get_embedding_dimension()
            current_provider = self.embedding_manager.get_current_provider_info()
            collection_name = "sermon_analytics"

            try:
                # Try to get existing collection
                existing_collection = self.client.get_collection(name=collection_name)
                existing_metadata = existing_collection.metadata or {}
                stored_dimensions = existing_metadata.get("embedding_dimensions")
                stored_provider = existing_metadata.get("embedding_provider", "unknown")
                stored_model = existing_metadata.get("embedding_model", "unknown")

                # Check for dimension mismatch
                if stored_dimensions and str(current_dimensions) != str(stored_dimensions):
                    logger.warning("EMBEDDING MODEL CHANGED DETECTED!")
                    logger.warning(
                        f"   Previous: {stored_provider}/{stored_model} ({stored_dimensions}D)"
                    )
                    logger.warning(
                        f"   Current:  {current_provider['provider']}/{current_provider['model']} "
                        f"({current_dimensions}D)"
                    )
                    logger.warning(
                        f"   Dimension mismatch detected: {stored_dimensions}D -> "
                        f"{current_dimensions}D"
                    )
                    logger.warning(
                        "   Automatically resetting vector database to prevent conflicts..."
                    )

                    # Delete the incompatible collection
                    self.client.delete_collection(name=collection_name)
                    logger.info("   Old vector database cleared successfully")

                    # Create new collection with correct dimensions
                    self.collection = self.client.create_collection(
                        name=collection_name,
                        metadata={
                            "description": "SermonAudio analytics data for RAG queries",
                            "embedding_provider": current_provider['provider'],
                            "embedding_model": current_provider['model'],
                            "embedding_dimensions": str(current_dimensions),
                            "created_at": datetime.now().isoformat(),
                            "reset_reason": (
                                f"Dimension mismatch: {stored_dimensions}D -> {current_dimensions}D"
                            )
                        }
                    )
                    logger.info(
                        f"   New vector database created with {current_dimensions}D embeddings"
                    )
                    logger.info(
                        "   The analytics chat system will need to re-index any existing data"
                    )
                    self.reset_notice = (
                        "The analytics vector database was reset because the embedding "
                        f"model changed ({stored_dimensions}D -> {current_dimensions}D). "
                        "Previously indexed data was cleared and will be re-indexed on "
                        "the next data load."
                    )

                elif (
                    stored_provider != current_provider['provider']
                    or stored_model != current_provider['model']
                ):
                    # Same dimensions but different provider/model - update metadata but keep data
                    logger.info("Embedding provider/model changed (same dimensions)")
                    logger.info(f"   Previous: {stored_provider}/{stored_model}")
                    logger.info(
                        f"   Current:  {current_provider['provider']}/{current_provider['model']}"
                    )
                    logger.info(
                        f"   Keeping existing data (dimensions unchanged: {current_dimensions}D)"
                    )

                    self.collection = existing_collection
                    # Update metadata to reflect the new provider
                    self.collection.modify(metadata={
                        **existing_metadata,
                        "embedding_provider": current_provider['provider'],
                        "embedding_model": current_provider['model'],
                        "last_updated": datetime.now().isoformat()
                    })
                else:
                    # Same provider and dimensions - use existing collection
                    logger.info(
                        f"Using existing vector database ({current_dimensions}D embeddings)"
                    )
                    self.collection = existing_collection

            except Exception:
                # Collection doesn't exist - create new one
                logger.info(
                    f"Creating new vector database with {current_dimensions}D embeddings"
                )
                self.collection = self.client.create_collection(
                    name=collection_name,
                    metadata={
                        "description": "SermonAudio analytics data for RAG queries",
                        "embedding_provider": current_provider['provider'],
                        "embedding_model": current_provider['model'],
                        "embedding_dimensions": str(current_dimensions),
                        "created_at": datetime.now().isoformat()
                    }
                )

            logger.info("RAG system initialized successfully")

        except Exception as e:
            logger.error(f"Failed to initialize RAG system: {e}")
            raise

    def _get_embeddings(self, texts: list[str]) -> list[list[float]]:
        """Get embeddings for texts using the configured embedding manager"""
        if not self.embedding_manager:
            raise RuntimeError("Embedding manager not initialized")

        try:
            return self.embedding_manager.get_embeddings(texts)
        except Exception as e:
            logger.error(f"Failed to get embeddings: {e}")
            raise

    def _reset_database_for_dimension_mismatch(self) -> None:
        """Reset the vector database to resolve dimension mismatches"""
        try:
            collection_name = "sermon_analytics"
            current_provider = self.embedding_manager.get_current_provider_info()
            current_dimensions = self.embedding_manager.get_embedding_dimension()

            # Delete the incompatible collection
            self.client.delete_collection(name=collection_name)
            logger.info("   Deleted incompatible vector database")

            # Create new collection with correct dimensions
            self.collection = self.client.create_collection(
                name=collection_name,
                metadata={
                    "description": "SermonAudio analytics data for RAG queries",
                    "embedding_provider": current_provider['provider'],
                    "embedding_model": current_provider['model'],
                    "embedding_dimensions": str(current_dimensions),
                    "created_at": datetime.now().isoformat(),
                    "reset_reason": (
                        "Automatic reset due to dimension mismatch during data insertion"
                    )
                }
            )
            logger.info(
                f"   Created new vector database with {current_dimensions}D embeddings"
            )

        except Exception as e:
            logger.error(f"Failed to reset database: {e}")
            raise

    def add_analytics_data(self, analytics_data: list[dict[str, Any]]) -> None:
        """Add analytics data to the vector database"""
        if not analytics_data:
            return

        documents = []
        metadatas = []
        ids = []

        for item in analytics_data:
            # Create a searchable text representation
            doc_text = self._create_document_text(item)
            documents.append(doc_text)

            # Prepare metadata (ChromaDB requires all values to be strings/numbers)
            metadata = self._prepare_metadata(item)
            metadatas.append(metadata)

            # Create unique ID
            sermon_id = item.get('sermon_id', str(uuid.uuid4()))
            ids.append(f"sermon_{sermon_id}")

        try:
            # Get embeddings for documents
            embeddings = self._get_embeddings(documents)

            # Upsert so a data refresh replaces existing sermon_{id} rows instead of
            # colliding with them
            self.collection.upsert(
                documents=documents,
                embeddings=embeddings,
                metadatas=metadatas,
                ids=ids
            )

            logger.info(f"Upserted {len(documents)} analytics records to vector database")

        except Exception as e:
            error_msg = str(e)

            # Check if this is a dimension mismatch error
            if "expecting embedding with dimension" in error_msg:
                logger.warning("DIMENSION MISMATCH DETECTED during data insertion!")
                logger.warning(f"   Error: {error_msg}")

                # Extract expected and actual dimensions from error message
                import re
                match = re.search(
                    r"expecting embedding with dimension of (\d+), got (\d+)", error_msg
                )
                if match:
                    expected_dim = match.group(1)
                    actual_dim = match.group(2)
                    logger.warning(f"   Expected: {expected_dim}D, Got: {actual_dim}D")

                logger.warning(
                    "   Automatically resetting vector database to fix dimension mismatch..."
                )

                try:
                    # Reset the database
                    self._reset_database_for_dimension_mismatch()
                    self.reset_notice = (
                        "The analytics vector database was reset because stored "
                        "embeddings did not match the current embedding model "
                        "dimensions. Previously indexed data was cleared and has been "
                        "re-indexed from the freshly loaded data."
                    )

                    # Retry the operation
                    logger.info("   Retrying data insertion with reset database...")
                    self.collection.upsert(
                        documents=documents,
                        embeddings=embeddings,
                        metadatas=metadatas,
                        ids=ids
                    )

                    logger.info(
                        f"   Successfully upserted {len(documents)} analytics records "
                        "after database reset"
                    )
                    return

                except Exception as retry_error:
                    logger.error(
                        f"   Failed to add data even after database reset: {retry_error}"
                    )
                    raise RuntimeError(
                        f"Database reset failed to resolve dimension mismatch: {retry_error}"
                    ) from e

            logger.error(f"Failed to add analytics data: {e}")
            raise

    def _create_document_text(self, item: dict[str, Any]) -> str:
        """Create searchable text representation of analytics data"""
        text_parts = []

        # Basic information
        text_parts.append(f"Sermon: {item.get('title', 'Unknown Title')}")
        text_parts.append(f"Speaker: {item.get('speaker', 'Unknown Speaker')}")

        if item.get('series'):
            text_parts.append(f"Series: {item.get('series')}")

        if item.get('event_type'):
            text_parts.append(f"Event: {item.get('event_type')}")

        # Keywords
        if item.get('keywords'):
            keywords = item['keywords']
            if isinstance(keywords, list):
                text_parts.append(f"Keywords: {', '.join(keywords)}")
            else:
                text_parts.append(f"Keywords: {keywords}")

        # Analytics metrics
        text_parts.append(f"Views: {item.get('views', 0)}")
        text_parts.append(f"Listens: {item.get('listens', 0)}")
        text_parts.append(f"Downloads: {item.get('downloads', 0)}")
        text_parts.append(f"Duration: {item.get('duration_minutes', 0)} minutes")

        # Engagement metrics
        engagement = item.get('engagement_score', 0)
        text_parts.append(f"Engagement score: {engagement:.2f}")

        completion = item.get('watch_time_avg', 0)
        text_parts.append(f"Average completion rate: {completion:.1%}")

        # Date information
        if item.get('date_preached'):
            text_parts.append(f"Preached on: {item.get('date_preached')}")

        return ". ".join(text_parts)

    def _prepare_metadata(self, item: dict[str, Any]) -> dict[str, Any]:
        """Prepare metadata for ChromaDB (only strings and numbers allowed)"""
        metadata = {}

        # String fields
        string_fields = [
            'sermon_id', 'title', 'speaker', 'series', 'event_type',
            'date_preached', 'date_uploaded',
        ]
        for field in string_fields:
            if item.get(field):
                metadata[field] = str(item[field])

        # Numeric fields
        numeric_fields = [
            'views', 'listens', 'downloads', 'duration_minutes',
            'engagement_score', 'watch_time_avg',
        ]
        for field in numeric_fields:
            if field in item:
                try:
                    metadata[field] = float(item[field])
                except (ValueError, TypeError):
                    pass

        # Keywords as string
        if item.get('keywords'):
            keywords = item['keywords']
            if isinstance(keywords, list):
                metadata['keywords'] = ', '.join(str(k) for k in keywords)
            else:
                metadata['keywords'] = str(keywords)

        return metadata

    def query_analytics(
        self,
        question: str,
        n_results: int | None = None,
        history: list[dict[str, str]] | None = None,
    ) -> dict[str, Any]:
        """Query the analytics data using natural language.

        Retrieves a bounded slice of the collection (up to MAX_RETRIEVAL_WIDTH rows),
        aggregates dataset-wide stats as grounding data, and asks the configured LLM
        to answer strictly from that context. Falls back to the keyword template
        answers, marked "(offline mode)", when the LLM call fails.
        """
        try:
            # Get query embedding
            query_embeddings = self._get_embeddings([question])

            # Widen retrieval beyond the old top-5 so aggregate questions see real data
            if n_results is None:
                try:
                    total = self.collection.count()
                except Exception:
                    total = 0
                n_results = max(1, min(total, MAX_RETRIEVAL_WIDTH))

            # Query the vector database
            results = self.collection.query(
                query_embeddings=query_embeddings,
                n_results=n_results
            )

            if not results['documents'] or not results['documents'][0]:
                return {
                    'question': question,
                    'answer': (
                        "I couldn't find any relevant sermon analytics data for your question."
                    ),
                    'relevant_sermons': [],
                    'data_source': 'rag_system'
                }

            try:
                context_block = self._build_context_block(question, results)
                answer = self._generate_llm_answer(question, context_block, history)
                data_source = 'llm'
            except (Exception, SystemExit) as e:
                # OllamaProvider calls sys.exit on missing models; keep the UI alive
                logger.warning(f"LLM answer failed, using offline template: {e}")
                answer = self._generate_answer(question, results) + "\n\n(offline mode)"
                data_source = 'offline_template'

            return {
                'question': question,
                'answer': answer,
                'relevant_sermons': self._format_relevant_sermons(results),
                'data_source': data_source,
                'timestamp': datetime.now().isoformat()
            }

        except Exception as e:
            error_msg = str(e)

            # Check if this is a dimension mismatch error
            if "expecting embedding with dimension" in error_msg:
                logger.warning("DIMENSION MISMATCH DETECTED during query!")
                logger.warning(f"   Error: {error_msg}")
                logger.warning(
                    "   Database reset is needed. Please reinitialize the RAG system."
                )

                return {
                    'question': question,
                    'answer': (
                        "The vector database has a dimension mismatch and needs to be reset. "
                        "This usually happens when the embedding model is changed. "
                        "Please refresh the page or restart the application to automatically fix "
                        "this."
                    ),
                    'relevant_sermons': [],
                    'data_source': 'dimension_mismatch_error'
                }

            logger.error(f"Failed to query analytics: {e}")
            return {
                'question': question,
                'answer': f"Sorry, I encountered an error while searching: {e}",
                'relevant_sermons': [],
                'data_source': 'error'
            }

    def _build_context_block(self, question: str, results: dict) -> str:
        """Build the data-only context block that grounds the LLM answer"""
        metadatas = results['metadatas'][0] or []
        lines: list[str] = []

        aggregates = self._compute_dataset_aggregates()
        if aggregates:
            lines.append("Dataset-wide totals (computed over every indexed sermon):")
            lines.append(f"- Sermons indexed: {aggregates['total_sermons']}")
            lines.append(f"- Total views: {aggregates['total_views']:,}")
            lines.append(f"- Total listens: {aggregates['total_listens']:,}")
            lines.append(f"- Total downloads: {aggregates['total_downloads']:,}")
            lines.append(f"- Average views per sermon: {aggregates['avg_views']:,.1f}")
            lines.append(f"- Average listens per sermon: {aggregates['avg_listens']:,.1f}")
            lines.append(
                f"- Average engagement score: {aggregates['avg_engagement']:.2f}"
            )
            lines.append(
                f"- Average completion rate: {aggregates['avg_completion']:.1%}"
            )
            if aggregates['speakers']:
                lines.append("Per-speaker totals:")
                for speaker, stats in aggregates['speakers']:
                    lines.append(
                        f"- {speaker}: {stats['count']} sermons, "
                        f"{stats['views']:,} views, {stats['listens']:,} listens"
                    )

        shown = metadatas[:MAX_PROMPT_SERMONS]
        lines.append("")
        header = (
            f"Sermons most relevant to the question ({len(metadatas)} retrieved"
            f", showing {len(shown)}):"
            if len(metadatas) > len(shown)
            else f"Sermons most relevant to the question ({len(shown)} retrieved):"
        )
        lines.append(header)
        for i, m in enumerate(shown, 1):
            completion = float(m.get('watch_time_avg', 0) or 0)
            lines.append(
                f"{i}. {m.get('title', 'Unknown Title')} | "
                f"speaker: {m.get('speaker', 'Unknown Speaker')} | "
                f"series: {m.get('series', 'N/A')} | "
                f"date: {m.get('date_preached', 'N/A')} | "
                f"views: {int(float(m.get('views', 0) or 0)):,} | "
                f"listens: {int(float(m.get('listens', 0) or 0)):,} | "
                f"downloads: {int(float(m.get('downloads', 0) or 0)):,} | "
                f"engagement: {float(m.get('engagement_score', 0) or 0):.2f} | "
                f"completion: {completion:.1%} | "
                f"keywords: {m.get('keywords', 'N/A')}"
            )

        return "\n".join(lines)

    def _compute_dataset_aggregates(self) -> dict[str, Any]:
        """Compute true totals and averages across every row in the collection"""
        try:
            data = self.collection.get(include=['metadatas'])
            metadatas = data.get('metadatas') or []
        except Exception as e:
            logger.warning(f"Failed to load full dataset for aggregation: {e}")
            return {}

        if not metadatas:
            return {}

        def _num(m: dict, key: str) -> float:
            try:
                return float(m.get(key, 0) or 0)
            except (TypeError, ValueError):
                return 0.0

        count = len(metadatas)
        total_views = sum(_num(m, 'views') for m in metadatas)
        total_listens = sum(_num(m, 'listens') for m in metadatas)
        total_downloads = sum(_num(m, 'downloads') for m in metadatas)

        speakers: dict[str, dict[str, float]] = {}
        for m in metadatas:
            speaker = str(m.get('speaker') or 'Unknown Speaker')
            stats = speakers.setdefault(speaker, {'count': 0, 'views': 0, 'listens': 0})
            stats['count'] += 1
            stats['views'] += _num(m, 'views')
            stats['listens'] += _num(m, 'listens')

        ranked_speakers = sorted(
            speakers.items(), key=lambda item: item[1]['views'], reverse=True
        )[:5]

        return {
            'total_sermons': count,
            'total_views': int(total_views),
            'total_listens': int(total_listens),
            'total_downloads': int(total_downloads),
            'avg_views': total_views / count,
            'avg_listens': total_listens / count,
            'avg_engagement': sum(_num(m, 'engagement_score') for m in metadatas) / count,
            'avg_completion': sum(_num(m, 'watch_time_avg') for m in metadatas) / count,
            'speakers': ranked_speakers,
        }

    def _generate_llm_answer(
        self,
        question: str,
        context_block: str,
        history: list[dict[str, str]] | None = None,
    ) -> str:
        """Answer the question via LLMManager using only the provided context"""
        if self.llm_manager is None:
            raise RuntimeError("LLM manager unavailable")

        messages: list[dict[str, str]] = [{
            'role': 'system',
            'content': (
                "You are a sermon analytics assistant inside the SermonPilot app. "
                "Answer the user's question using ONLY the sermon analytics data "
                "provided in the conversation. Never invent, estimate, or extrapolate "
                "numbers that are not present in that data. If the data cannot answer "
                "the question, say so plainly and briefly summarize what the data does "
                "show. Keep answers concise and concrete."
            ),
        }]

        for entry in (history or [])[-MAX_HISTORY_PAIRS * 2:]:
            role = entry.get('role')
            content = entry.get('content')
            if role in ('user', 'assistant') and content:
                messages.append({'role': role, 'content': content})

        messages.append({
            'role': 'user',
            'content': f"{context_block}\n\nQuestion: {question}",
        })

        return self.llm_manager.chat(messages, operation="analytics_chat")

    def _generate_answer(self, question: str, results: dict) -> str:
        """Generate a template answer from retrieved data (offline fallback only)"""
        documents = results['documents'][0]
        metadatas = results['metadatas'][0]

        if not documents:
            return "I couldn't find relevant data to answer your question."

        # Analyze the question to determine what type of answer to generate
        question_lower = question.lower()

        # Handle different types of questions
        if any(word in question_lower for word in ['average', 'avg', 'mean']):
            return self._generate_average_answer(question, metadatas)
        elif any(word in question_lower for word in ['top', 'best', 'highest', 'most']):
            return self._generate_top_answer(question, metadatas)
        elif any(word in question_lower for word in ['total', 'sum', 'overall']):
            return self._generate_total_answer(question, metadatas)
        elif any(word in question_lower for word in ['speaker', 'pastor', 'preacher']):
            return self._generate_speaker_answer(question, metadatas)
        elif any(word in question_lower for word in ['series']):
            return self._generate_series_answer(question, metadatas)
        else:
            return self._generate_general_answer(question, metadatas)

    def _generate_average_answer(self, question: str, metadatas: list[dict]) -> str:
        """Generate answer for average-type questions"""
        question_lower = question.lower()

        if 'view' in question_lower:
            views = [m.get('views', 0) for m in metadatas if m.get('views')]
            if views:
                avg_views = sum(views) / len(views)
                return (
                    f"The average number of views across the relevant sermons is "
                    f"{avg_views:.0f}."
                )

        if 'listen' in question_lower:
            listens = [m.get('listens', 0) for m in metadatas if m.get('listens')]
            if listens:
                avg_listens = sum(listens) / len(listens)
                return (
                    f"The average number of listens across the relevant sermons is "
                    f"{avg_listens:.0f}."
                )

        if 'engagement' in question_lower:
            engagement = [
                m.get('engagement_score', 0)
                for m in metadatas if m.get('engagement_score')
            ]
            if engagement:
                avg_engagement = sum(engagement) / len(engagement)
                return (
                    f"The average engagement score across the relevant sermons is "
                    f"{avg_engagement:.2f}."
                )

        if 'completion' in question_lower or 'watch time' in question_lower:
            completion = [m.get('watch_time_avg', 0) for m in metadatas if m.get('watch_time_avg')]
            if completion:
                avg_completion = sum(completion) / len(completion)
                return (
                    f"The average completion rate across the relevant sermons is "
                    f"{avg_completion:.1%}."
                )

        return (
            f"I found {len(metadatas)} relevant sermons but couldn't calculate the "
            "specific average you're looking for."
        )

    def _generate_top_answer(self, question: str, metadatas: list[dict]) -> str:
        """Generate answer for top/best questions"""
        question_lower = question.lower()

        if 'view' in question_lower:
            sorted_by_views = sorted(metadatas, key=lambda x: x.get('views', 0), reverse=True)
            if sorted_by_views:
                top = sorted_by_views[0]
                return (
                    f"The sermon with the most views is '{top.get('title', 'Unknown')}' "
                    f"by {top.get('speaker', 'Unknown Speaker')} "
                    f"with {top.get('views', 0)} views."
                )

        if 'engagement' in question_lower:
            sorted_by_engagement = sorted(
                metadatas, key=lambda x: x.get('engagement_score', 0), reverse=True
            )
            if sorted_by_engagement:
                top = sorted_by_engagement[0]
                return (
                    f"The sermon with the highest engagement is '{top.get('title', 'Unknown')}' "
                    f"by {top.get('speaker', 'Unknown Speaker')} with an engagement score of "
                    f"{top.get('engagement_score', 0):.2f}."
                )

        return (
            f"I found {len(metadatas)} relevant sermons. "
            "Could you be more specific about what metric you'd like to see ranked?"
        )

    def _generate_total_answer(self, question: str, metadatas: list[dict]) -> str:
        """Generate answer for total/sum questions"""
        question_lower = question.lower()

        if 'view' in question_lower:
            total_views = sum(m.get('views', 0) for m in metadatas)
            return (
                f"The total number of views across {len(metadatas)} relevant sermons "
                f"is {total_views:,}."
            )

        if 'listen' in question_lower:
            total_listens = sum(m.get('listens', 0) for m in metadatas)
            return (
                f"The total number of listens across {len(metadatas)} relevant sermons "
                f"is {total_listens:,}."
            )

        return (
            f"I found {len(metadatas)} relevant sermons. "
            "Could you specify which metric you'd like totaled?"
        )

    def _generate_speaker_answer(self, question: str, metadatas: list[dict]) -> str:
        """Generate answer for speaker-related questions"""
        speaker_stats = {}
        for m in metadatas:
            speaker = m.get('speaker', 'Unknown')
            if speaker not in speaker_stats:
                speaker_stats[speaker] = {'count': 0, 'total_views': 0, 'total_listens': 0}
            speaker_stats[speaker]['count'] += 1
            speaker_stats[speaker]['total_views'] += m.get('views', 0)
            speaker_stats[speaker]['total_listens'] += m.get('listens', 0)

        # Sort by most sermons
        sorted_speakers = sorted(speaker_stats.items(), key=lambda x: x[1]['count'], reverse=True)

        if sorted_speakers:
            top_speaker, stats = sorted_speakers[0]
            return (
                f"Among the relevant sermons, {top_speaker} has {stats['count']} sermons "
                f"with {stats['total_views']:,} total views and "
                f"{stats['total_listens']:,} total listens."
            )

        return "I couldn't find speaker information in the relevant sermons."

    def _generate_series_answer(self, question: str, metadatas: list[dict]) -> str:
        """Generate answer for series-related questions"""
        series_stats = {}
        for m in metadatas:
            series = m.get('series')
            if series:
                if series not in series_stats:
                    series_stats[series] = {'count': 0, 'total_views': 0}
                series_stats[series]['count'] += 1
                series_stats[series]['total_views'] += m.get('views', 0)

        if series_stats:
            # Sort by total views
            sorted_series = sorted(
                series_stats.items(), key=lambda x: x[1]['total_views'], reverse=True
            )
            top_series, stats = sorted_series[0]
            return (
                f"The top performing series is '{top_series}' with {stats['count']} sermons "
                f"and {stats['total_views']:,} total views."
            )

        return "I couldn't find series information in the relevant sermons."

    def _generate_general_answer(self, question: str, metadatas: list[dict]) -> str:
        """Generate a general answer based on the data"""
        if not metadatas:
            return "I couldn't find relevant data to answer your question."

        total_views = sum(m.get('views', 0) for m in metadatas)
        total_listens = sum(m.get('listens', 0) for m in metadatas)

        return (
            f"I found {len(metadatas)} relevant sermons with a total of {total_views:,} "
            f"views and {total_listens:,} listens. "
            "The sermons cover various topics and speakers."
        )

    def _format_relevant_sermons(self, results: dict) -> list[dict[str, Any]]:
        """Format relevant sermons for display"""
        metadatas = results['metadatas'][0] if results['metadatas'] else []
        distances = results['distances'][0] if results['distances'] else []

        sermons = []
        for i, metadata in enumerate(metadatas):
            sermon = {
                'title': metadata.get('title', 'Unknown'),
                'speaker': metadata.get('speaker', 'Unknown'),
                'views': metadata.get('views', 0),
                'listens': metadata.get('listens', 0),
                'relevance_score': 1 - distances[i] if i < len(distances) else 0
            }
            sermons.append(sermon)

        return sermons

    def get_collection_stats(self) -> dict[str, Any]:
        """Get statistics about the vector database collection"""
        try:
            count = self.collection.count()
            provider_info = self.embedding_manager.get_current_provider_info()
            return {
                'total_documents': count,
                'collection_name': self.collection.name,
                'embedding_provider': provider_info['provider'],
                'embedding_model': provider_info['model'],
                'embedding_dimensions': provider_info['dimensions'],
                'last_updated': datetime.now().isoformat()
            }
        except Exception as e:
            logger.error(f"Failed to get collection stats: {e}")
            return {'error': str(e)}

    def get_embedding_provider_info(self) -> dict[str, Any]:
        """Get detailed information about the current embedding provider"""
        if self.embedding_manager:
            provider_info = self.embedding_manager.get_current_provider_info()
            return {
                'current_provider': provider_info,
                'available_fallbacks': len(self.embedding_manager.fallback_providers),
                'embedding_dimensions': self.embedding_manager.get_embedding_dimension()
            }
        else:
            return {'error': 'Embedding manager not initialized'}

    def switch_embedding_provider(self, new_config: dict[str, Any]) -> bool:
        """Switch to a new embedding provider configuration"""
        try:
            # Create new embedding manager
            new_manager = create_embedding_manager(new_config)
            old_provider = self.embedding_manager.get_current_provider_info()

            # Check if dimensions match (important for existing data)
            old_dim = self.embedding_manager.get_embedding_dimension()
            new_dim = new_manager.get_embedding_dimension()

            if old_dim != new_dim:
                logger.warning(f"Dimension mismatch: old={old_dim}, new={new_dim}. "
                              "Existing embeddings may not be compatible.")

            # Update the manager
            self.embedding_manager = new_manager
            self.embedding_config = new_config

            new_provider = self.embedding_manager.get_current_provider_info()
            logger.info(f"Switched embedding provider from {old_provider['provider']} "
                       f"to {new_provider['provider']}")

            return True

        except Exception as e:
            logger.error(f"Failed to switch embedding provider: {e}")
            return False

    def clear_collection(self) -> None:
        """Clear all data from the collection"""
        try:
            # Delete the collection and recreate it
            self.client.delete_collection(name="sermon_analytics")
            self.collection = self.client.get_or_create_collection(
                name="sermon_analytics",
                metadata={"description": "SermonAudio analytics data for RAG queries"}
            )
            logger.info("Collection cleared successfully")
        except Exception as e:
            logger.error(f"Failed to clear collection: {e}")
            raise


def initialize_rag_system_with_data(
    analytics_data: list[dict[str, Any]],
    embedding_config: dict[str, Any] | None = None,
    llm_config: dict[str, Any] | None = None,
) -> SermonAnalyticsRAG:
    """Initialize RAG system and populate with analytics data"""
    rag = SermonAnalyticsRAG(
        embedding_config=embedding_config,
        llm_config=llm_config,
    )

    if analytics_data:
        rag.add_analytics_data(analytics_data)

    return rag


def create_rag_with_config(config: dict[str, Any]) -> SermonAnalyticsRAG:
    """Create RAG system from full configuration (including embedding config)"""
    embedding_config = config.get('embeddings', {})
    db_path = config.get('rag_system', {}).get('vector_db_path', 'analytics_vector_db')

    return SermonAnalyticsRAG(
        db_path=db_path,
        embedding_config=embedding_config,
        llm_config=config,
    )
